window.WORLD_CUP_PLAYER_STATS = {
  "generatedAt": "2026-06-26T21:38:05+00:00",
  "sources": [
    {
      "label": "Guardian Golden Boot",
      "url": "https://www.theguardian.com/football/ng-interactive/2026/jun/04/golden-boot-world-cup-2026-top-goalscorers-winner"
    },
    {
      "label": "Guardian data feed",
      "url": "https://mobile.guardianapis.com/sport/football/competitions/700/golden-boot"
    }
  ],
  "players": [
    {
      "rank": 1,
      "player": "Lionel Messi",
      "team": "Argentina",
      "position": "FW",
      "goals": 5,
      "assists": 0,
      "points": 5,
      "matches": 2,
      "minutes": 188,
      "goalsPer90": 2.4,
      "pointsPer90": 2.4
    },
    {
      "rank": 2,
      "player": "Kylian Mbappe",
      "team": "France",
      "position": "FW",
      "goals": 4,
      "assists": 2,
      "points": 6,
      "matches": 3,
      "minutes": 290,
      "goalsPer90": 1.2,
      "pointsPer90": 1.9
    },
    {
      "rank": 3,
      "player": "Ousmane Dembele",
      "team": "France",
      "position": "MID",
      "goals": 4,
      "assists": 1,
      "points": 5,
      "matches": 3,
      "minutes": 226,
      "goalsPer90": 1.6,
      "pointsPer90": 2.0
    },
    {
      "rank": 4,
      "player": "Jose Vinicius Junior",
      "team": "Brazil",
      "position": "FW",
      "goals": 4,
      "assists": 1,
      "points": 5,
      "matches": 3,
      "minutes": 294,
      "goalsPer90": 1.2,
      "pointsPer90": 1.5
    },
    {
      "rank": 5,
      "player": "Erling Braut Haaland",
      "team": "Norway",
      "position": "FW",
      "goals": 4,
      "assists": 0,
      "points": 4,
      "matches": 3,
      "minutes": 208,
      "goalsPer90": 1.7,
      "pointsPer90": 1.7
    },
    {
      "rank": 6,
      "player": "Deniz Undav",
      "team": "Germany",
      "position": "FW",
      "goals": 3,
      "assists": 2,
      "points": 5,
      "matches": 3,
      "minutes": 107,
      "goalsPer90": 2.5,
      "pointsPer90": 4.2
    },
    {
      "rank": 7,
      "player": "Johan Manzambi",
      "team": "Switzerland",
      "position": "MID",
      "goals": 3,
      "assists": 1,
      "points": 4,
      "matches": 3,
      "minutes": 147,
      "goalsPer90": 1.8,
      "pointsPer90": 2.4
    },
    {
      "rank": 8,
      "player": "Ismaila Sarr",
      "team": "Senegal",
      "position": "FW",
      "goals": 3,
      "assists": 1,
      "points": 4,
      "matches": 3,
      "minutes": 275,
      "goalsPer90": 1.0,
      "pointsPer90": 1.3
    },
    {
      "rank": 9,
      "player": "Brian Brobbey",
      "team": "Netherlands",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 3,
      "minutes": 168,
      "goalsPer90": 1.6,
      "pointsPer90": 1.6
    },
    {
      "rank": 10,
      "player": "Matheus Cunha",
      "team": "Brazil",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 3,
      "minutes": 191,
      "goalsPer90": 1.4,
      "pointsPer90": 1.4
    },
    {
      "rank": 11,
      "player": "Ismael Saibari",
      "team": "Morocco",
      "position": "MID",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 3,
      "minutes": 255,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 12,
      "player": "Jonathan David",
      "team": "Canada",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 3,
      "minutes": 271,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 13,
      "player": "Mikel Oyarzabal",
      "team": "Spain",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 2,
      "minutes": 144,
      "goalsPer90": 1.2,
      "pointsPer90": 1.9
    },
    {
      "rank": 14,
      "player": "Crysencio Summerville",
      "team": "Netherlands",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 147,
      "goalsPer90": 1.2,
      "pointsPer90": 1.8
    },
    {
      "rank": 15,
      "player": "Maximiliano Araujo",
      "team": "Uruguay",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 2,
      "minutes": 174,
      "goalsPer90": 1.0,
      "pointsPer90": 1.6
    },
    {
      "rank": 16,
      "player": "Pape Gueye",
      "team": "Senegal",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 186,
      "goalsPer90": 1.0,
      "pointsPer90": 1.5
    },
    {
      "rank": 17,
      "player": "Ruben Vargas",
      "team": "Switzerland",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 194,
      "goalsPer90": 0.9,
      "pointsPer90": 1.4
    },
    {
      "rank": 18,
      "player": "Ayase Ueda",
      "team": "Japan",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 245,
      "goalsPer90": 0.7,
      "pointsPer90": 1.1
    },
    {
      "rank": 19,
      "player": "Cody Gakpo",
      "team": "Netherlands",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 268,
      "goalsPer90": 0.7,
      "pointsPer90": 1.0
    },
    {
      "rank": 20,
      "player": "Ermin Mahmic",
      "team": "Bosnia and Herzegovina",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 39,
      "goalsPer90": 4.6,
      "pointsPer90": 4.6
    },
    {
      "rank": 21,
      "player": "Anthony Elanga",
      "team": "Sweden",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 149,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 22,
      "player": "Nicolas Pepe",
      "team": "Ivory Coast",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 164,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 23,
      "player": "Folarin Balogun",
      "team": "United States",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 180,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 24,
      "player": "Cyle Larin",
      "team": "Canada",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 187,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 25,
      "player": "Elijah Just",
      "team": "New Zealand",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 190,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 26,
      "player": "Cristiano Ronaldo",
      "team": "Portugal",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 202,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 27,
      "player": "Harry Kane",
      "team": "England",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 204,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 28,
      "player": "Daniel Munoz",
      "team": "Colombia",
      "position": "DEF",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 207,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 29,
      "player": "Kai Havertz",
      "team": "Germany",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 256,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 30,
      "player": "Julian Quinones",
      "team": "Mexico",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 270,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 31,
      "player": "Daichi Kamada",
      "team": "Japan",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 278,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 32,
      "player": "Yasin Ayari",
      "team": "Sweden",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 3,
      "minutes": 286,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 33,
      "player": "Iliman-Cheikh Ndiaye",
      "team": "Senegal",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 3,
      "minutes": 56,
      "goalsPer90": 1.6,
      "pointsPer90": 4.8
    },
    {
      "rank": 34,
      "player": "Nathan-Dylan Saliba",
      "team": "Canada",
      "position": "MID",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 3,
      "minutes": 143,
      "goalsPer90": 0.6,
      "pointsPer90": 1.9
    },
    {
      "rank": 35,
      "player": "Mohamed Salah",
      "team": "Egypt",
      "position": "MID",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 2,
      "minutes": 168,
      "goalsPer90": 0.5,
      "pointsPer90": 1.6
    },
    {
      "rank": 36,
      "player": "Breel Embolo",
      "team": "Switzerland",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 3,
      "minutes": 283,
      "goalsPer90": 0.3,
      "pointsPer90": 1.0
    },
    {
      "rank": 37,
      "player": "Alexander Isak",
      "team": "Sweden",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 3,
      "minutes": 296,
      "goalsPer90": 0.3,
      "pointsPer90": 0.9
    },
    {
      "rank": 38,
      "player": "Viktor Gyokeres",
      "team": "Sweden",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 3,
      "minutes": 303,
      "goalsPer90": 0.3,
      "pointsPer90": 0.9
    },
    {
      "rank": 39,
      "player": "Soufiane Rahimi",
      "team": "Morocco",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 54,
      "goalsPer90": 1.7,
      "pointsPer90": 3.3
    },
    {
      "rank": 40,
      "player": "Promise David",
      "team": "Canada",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 58,
      "goalsPer90": 1.6,
      "pointsPer90": 3.1
    },
    {
      "rank": 41,
      "player": "Bradley Barcola",
      "team": "France",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 136,
      "goalsPer90": 0.7,
      "pointsPer90": 1.3
    },
    {
      "rank": 42,
      "player": "Luis Romo",
      "team": "Mexico",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 141,
      "goalsPer90": 0.6,
      "pointsPer90": 1.3
    },
    {
      "rank": 43,
      "player": "Mostafa Ziko",
      "team": "Egypt",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 160,
      "goalsPer90": 0.6,
      "pointsPer90": 1.1
    },
    {
      "rank": 44,
      "player": "Nathaniel Brown",
      "team": "Germany",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 182,
      "goalsPer90": 0.5,
      "pointsPer90": 1.0
    },
    {
      "rank": 45,
      "player": "Sebastian Berhalter",
      "team": "United States",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 183,
      "goalsPer90": 0.5,
      "pointsPer90": 1.0
    },
    {
      "rank": 46,
      "player": "Baris Yilmaz",
      "team": "Turkey",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 196,
      "goalsPer90": 0.5,
      "pointsPer90": 0.9
    },
    {
      "rank": 47,
      "player": "Luis Diaz",
      "team": "Colombia",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 199,
      "goalsPer90": 0.5,
      "pointsPer90": 0.9
    },
    {
      "rank": 48,
      "player": "Ramin Rezaeian",
      "team": "Iran",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 205,
      "goalsPer90": 0.4,
      "pointsPer90": 0.9
    },
    {
      "rank": 49,
      "player": "Alex Freeman",
      "team": "United States",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 232,
      "goalsPer90": 0.4,
      "pointsPer90": 0.8
    },
    {
      "rank": 50,
      "player": "Felix Nmecha",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 250,
      "goalsPer90": 0.4,
      "pointsPer90": 0.7
    },
    {
      "rank": 51,
      "player": "Keito Nakamura",
      "team": "Japan",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 261,
      "goalsPer90": 0.3,
      "pointsPer90": 0.7
    },
    {
      "rank": 52,
      "player": "In-Beom Hwang",
      "team": "South Korea",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 287,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 53,
      "player": "Virgil van Dijk",
      "team": "Netherlands",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 298,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 54,
      "player": "Achraf Hakimi",
      "team": "Morocco",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 309,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 55,
      "player": "Kaan Ayhan",
      "team": "Turkey",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 12,
      "goalsPer90": 7.5,
      "pointsPer90": 7.5
    },
    {
      "rank": 56,
      "player": "Mattias Svanberg",
      "team": "Sweden",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 13,
      "goalsPer90": 6.9,
      "pointsPer90": 6.9
    },
    {
      "rank": 57,
      "player": "Mahmoud Trezeguet",
      "team": "Egypt",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 25,
      "goalsPer90": 3.6,
      "pointsPer90": 3.6
    },
    {
      "rank": 58,
      "player": "Gessime Yassine",
      "team": "Morocco",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 28,
      "goalsPer90": 3.2,
      "pointsPer90": 3.2
    },
    {
      "rank": 59,
      "player": "Jaminton Campaz",
      "team": "Colombia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 29,
      "goalsPer90": 3.1,
      "pointsPer90": 3.1
    },
    {
      "rank": 60,
      "player": "Rafael Leao",
      "team": "Portugal",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 37,
      "goalsPer90": 2.4,
      "pointsPer90": 2.4
    },
    {
      "rank": 61,
      "player": "Marcus Rashford",
      "team": "England",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 38,
      "goalsPer90": 2.4,
      "pointsPer90": 2.4
    },
    {
      "rank": 62,
      "player": "Helio Varela",
      "team": "Cape Verde",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 40,
      "goalsPer90": 2.2,
      "pointsPer90": 2.2
    },
    {
      "rank": 63,
      "player": "Ante Budimir",
      "team": "Croatia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 50,
      "goalsPer90": 1.8,
      "pointsPer90": 1.8
    },
    {
      "rank": 64,
      "player": "Ahmed Benbouali",
      "team": "Algeria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 52,
      "goalsPer90": 1.7,
      "pointsPer90": 1.7
    },
    {
      "rank": 65,
      "player": "Lamine Yamal",
      "team": "Spain",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 69,
      "goalsPer90": 1.3,
      "pointsPer90": 1.3
    },
    {
      "rank": 66,
      "player": "Hasan Al Haydos",
      "team": "Qatar",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 70,
      "goalsPer90": 1.3,
      "pointsPer90": 1.3
    },
    {
      "rank": 67,
      "player": "Jovo Lukic",
      "team": "Bosnia and Herzegovina",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 77,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 68,
      "player": "Mateo Chavez",
      "team": "Mexico",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 82,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 69,
      "player": "Marko Arnautovic",
      "team": "Austria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 88,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 70,
      "player": "Habib Diarra",
      "team": "Senegal",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 91,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 71,
      "player": "Hazem Mastouri",
      "team": "Tunisia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 93,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 72,
      "player": "Alvaro Fidalgo",
      "team": "Mexico",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 94,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 73,
      "player": "Thelonious Aasgaard",
      "team": "Norway",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 100,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 74,
      "player": "Giovanni Reyna",
      "team": "United States",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 75,
      "player": "Prado Mauricio",
      "team": "Paraguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 104,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 76,
      "player": "Petar Musa",
      "team": "Croatia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 116,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 77,
      "player": "Auston Trusty",
      "team": "United States",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 123,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 78,
      "player": "Aymen Hussein",
      "team": "Iraq",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 129,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 79,
      "player": "Ibrahim Mbaye",
      "team": "Senegal",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 137,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 80,
      "player": "Leo Ostigard",
      "team": "Norway",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 142,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 80,
      "player": "Marcus Pedersen",
      "team": "Norway",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 142,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 81,
      "player": "Hyeon-Gyu Oh",
      "team": "South Korea",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 145,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 81,
      "player": "Nico Schlotterbeck",
      "team": "Germany",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 145,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 82,
      "player": "Nilson Angulo",
      "team": "Ecuador",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 157,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 83,
      "player": "Amine Gouiri",
      "team": "Algeria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 158,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 84,
      "player": "Agustin Canobbio",
      "team": "Uruguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 160,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 85,
      "player": "Abbosbek Fayzullaev",
      "team": "Uzbekistan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 161,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 85,
      "player": "Junya Ito",
      "team": "Japan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 161,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 86,
      "player": "Emam Ashour",
      "team": "Egypt",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 163,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 87,
      "player": "Raul Jimenez",
      "team": "Mexico",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 164,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 87,
      "player": "Jude Bellingham",
      "team": "England",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 164,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 88,
      "player": "Thapelo Maseko",
      "team": "South Africa",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 167,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 88,
      "player": "Abdulelah Al Amri",
      "team": "Saudi Arabia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 167,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 89,
      "player": "Amad Diallo",
      "team": "Ivory Coast",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 169,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 90,
      "player": "Daizen Maeda",
      "team": "Japan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 171,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 90,
      "player": "Romano Schmid",
      "team": "Austria",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 171,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 91,
      "player": "Mohammed Mohebi",
      "team": "Iran",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 175,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 92,
      "player": "Kevin Lenini",
      "team": "Cape Verde",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 177,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 93,
      "player": "Alexandre Nuno Mendes",
      "team": "Portugal",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 178,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 94,
      "player": "Martin Baturina",
      "team": "Croatia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 182,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 94,
      "player": "Joao Neves",
      "team": "Portugal",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 182,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 95,
      "player": "Matias Galarza",
      "team": "Paraguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 199,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 96,
      "player": "Omar Rekik",
      "team": "Tunisia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 201,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 96,
      "player": "Wilson Isidor",
      "team": "Haiti",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 201,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 97,
      "player": "Yoane Wissa",
      "team": "DR Congo",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 202,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 97,
      "player": "Teboho Mokoena",
      "team": "South Africa",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 202,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 98,
      "player": "Kerim Alajbegovic",
      "team": "Bosnia and Herzegovina",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 203,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 98,
      "player": "Ali Olwan",
      "team": "Jordan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 203,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 99,
      "player": "Michal Sadilek",
      "team": "Czechia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 100,
      "player": "Finn Surman",
      "team": "New Zealand",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 206,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 101,
      "player": "Nestory Irankunda",
      "team": "Australia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 208,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 102,
      "player": "Caleb Yirenkyi",
      "team": "Ghana",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 209,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 102,
      "player": "Nizar Al Rashdan",
      "team": "Jordan",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 209,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 103,
      "player": "Desire Doue",
      "team": "France",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 218,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 104,
      "player": "Jamal Musiala",
      "team": "Germany",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 237,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 105,
      "player": "Livano Comenencia",
      "team": "Curacao",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 253,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 106,
      "player": "Connor Metcalfe",
      "team": "Australia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 255,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 107,
      "player": "Leroy Sane",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 268,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 108,
      "player": "John McGinn",
      "team": "Scotland",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 278,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 109,
      "player": "Franck Kessie",
      "team": "Ivory Coast",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 288,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 110,
      "player": "Jan Paul van Hecke",
      "team": "Netherlands",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 298,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 111,
      "player": "Ladislav Krejci",
      "team": "Czechia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 301,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 112,
      "player": "Gonzalo Plata",
      "team": "Ecuador",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 304,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 112,
      "player": "Granit Xhaka",
      "team": "Switzerland",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 304,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 113,
      "player": "Arda Guler",
      "team": "Turkey",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 314,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    }
  ]
};
