window.WORLD_CUP_PLAYER_STATS = {
  "generatedAt": "2026-07-19T20:34:06+00:00",
  "sources": [
    {
      "label": "Guardian Golden Boot",
      "url": "https://www.theguardian.com/football/ng-interactive/2026/jun/04/golden-boot-world-cup-2026-top-goalscorers-winner"
    },
    {
      "label": "Guardian data feed",
      "url": "https://mobile.guardianapis.com/sport/football/competitions/700/golden-boot"
    }
  ],
  "players": [
    {
      "rank": 1,
      "player": "Kylian Mbappe",
      "team": "France",
      "position": "FW",
      "goals": 10,
      "assists": 4,
      "points": 14,
      "matches": 8,
      "minutes": 770,
      "goalsPer90": 1.2,
      "pointsPer90": 1.6
    },
    {
      "rank": 2,
      "player": "Lionel Messi",
      "team": "Argentina",
      "position": "FW",
      "goals": 8,
      "assists": 4,
      "points": 12,
      "matches": 8,
      "minutes": 767,
      "goalsPer90": 0.9,
      "pointsPer90": 1.4
    },
    {
      "rank": 3,
      "player": "Jude Bellingham",
      "team": "England",
      "position": "MID",
      "goals": 7,
      "assists": 1,
      "points": 8,
      "matches": 8,
      "minutes": 696,
      "goalsPer90": 0.9,
      "pointsPer90": 1.0
    },
    {
      "rank": 4,
      "player": "Erling Braut Haaland",
      "team": "Norway",
      "position": "FW",
      "goals": 7,
      "assists": 0,
      "points": 7,
      "matches": 6,
      "minutes": 536,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 5,
      "player": "Ousmane Dembele",
      "team": "France",
      "position": "FW",
      "goals": 6,
      "assists": 2,
      "points": 8,
      "matches": 8,
      "minutes": 649,
      "goalsPer90": 0.8,
      "pointsPer90": 1.1
    },
    {
      "rank": 6,
      "player": "Harry Kane",
      "team": "England",
      "position": "FW",
      "goals": 6,
      "assists": 1,
      "points": 7,
      "matches": 8,
      "minutes": 729,
      "goalsPer90": 0.7,
      "pointsPer90": 0.9
    },
    {
      "rank": 7,
      "player": "Mikel Oyarzabal",
      "team": "Spain",
      "position": "FW",
      "goals": 5,
      "assists": 1,
      "points": 6,
      "matches": 8,
      "minutes": 655,
      "goalsPer90": 0.7,
      "pointsPer90": 0.8
    },
    {
      "rank": 8,
      "player": "Ismaila Sarr",
      "team": "Senegal",
      "position": "FW",
      "goals": 4,
      "assists": 1,
      "points": 5,
      "matches": 4,
      "minutes": 419,
      "goalsPer90": 0.9,
      "pointsPer90": 1.1
    },
    {
      "rank": 9,
      "player": "Julian Quinones",
      "team": "Mexico",
      "position": "FW",
      "goals": 4,
      "assists": 1,
      "points": 5,
      "matches": 5,
      "minutes": 440,
      "goalsPer90": 0.8,
      "pointsPer90": 1.0
    },
    {
      "rank": 10,
      "player": "Jose Vinicius Junior",
      "team": "Brazil",
      "position": "FW",
      "goals": 4,
      "assists": 1,
      "points": 5,
      "matches": 5,
      "minutes": 506,
      "goalsPer90": 0.7,
      "pointsPer90": 0.9
    },
    {
      "rank": 11,
      "player": "Bukayo Saka",
      "team": "England",
      "position": "MID",
      "goals": 3,
      "assists": 3,
      "points": 6,
      "matches": 8,
      "minutes": 409,
      "goalsPer90": 0.7,
      "pointsPer90": 1.3
    },
    {
      "rank": 12,
      "player": "Deniz Undav",
      "team": "Germany",
      "position": "FW",
      "goals": 3,
      "assists": 2,
      "points": 5,
      "matches": 4,
      "minutes": 175,
      "goalsPer90": 1.5,
      "pointsPer90": 2.6
    },
    {
      "rank": 13,
      "player": "Johan Manzambi",
      "team": "Switzerland",
      "position": "MID",
      "goals": 3,
      "assists": 2,
      "points": 5,
      "matches": 4,
      "minutes": 221,
      "goalsPer90": 1.2,
      "pointsPer90": 2.0
    },
    {
      "rank": 14,
      "player": "Romelu Lukaku",
      "team": "Belgium",
      "position": "FW",
      "goals": 3,
      "assists": 1,
      "points": 4,
      "matches": 6,
      "minutes": 279,
      "goalsPer90": 1.0,
      "pointsPer90": 1.3
    },
    {
      "rank": 15,
      "player": "Lautaro Martinez",
      "team": "Argentina",
      "position": "FW",
      "goals": 3,
      "assists": 1,
      "points": 4,
      "matches": 8,
      "minutes": 367,
      "goalsPer90": 0.7,
      "pointsPer90": 1.0
    },
    {
      "rank": 16,
      "player": "Cody Gakpo",
      "team": "Netherlands",
      "position": "FW",
      "goals": 3,
      "assists": 1,
      "points": 4,
      "matches": 4,
      "minutes": 394,
      "goalsPer90": 0.7,
      "pointsPer90": 0.9
    },
    {
      "rank": 17,
      "player": "Bradley Barcola",
      "team": "France",
      "position": "FW",
      "goals": 3,
      "assists": 1,
      "points": 4,
      "matches": 8,
      "minutes": 433,
      "goalsPer90": 0.6,
      "pointsPer90": 0.8
    },
    {
      "rank": 18,
      "player": "Brian Brobbey",
      "team": "Netherlands",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 4,
      "minutes": 245,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 19,
      "player": "Elijah Just",
      "team": "New Zealand",
      "position": "MID",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 3,
      "minutes": 292,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 20,
      "player": "Matheus Cunha",
      "team": "Brazil",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 5,
      "minutes": 324,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 21,
      "player": "Raul Jimenez",
      "team": "Mexico",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 5,
      "minutes": 349,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 22,
      "player": "Folarin Balogun",
      "team": "United States",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 5,
      "minutes": 352,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 23,
      "player": "Charles De Ketelaere",
      "team": "Belgium",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 6,
      "minutes": 381,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 24,
      "player": "Kai Havertz",
      "team": "Germany",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 4,
      "minutes": 388,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 25,
      "player": "Yoane Wissa",
      "team": "DR Congo",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 4,
      "minutes": 410,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 26,
      "player": "Ismael Saibari",
      "team": "Morocco",
      "position": "MID",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 6,
      "minutes": 411,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 27,
      "player": "Jonathan David",
      "team": "Canada",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 5,
      "minutes": 476,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 28,
      "player": "Cristiano Ronaldo",
      "team": "Portugal",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 5,
      "minutes": 491,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 29,
      "player": "Crysencio Summerville",
      "team": "Netherlands",
      "position": "FW",
      "goals": 2,
      "assists": 2,
      "points": 4,
      "matches": 4,
      "minutes": 281,
      "goalsPer90": 0.6,
      "pointsPer90": 1.3
    },
    {
      "rank": 30,
      "player": "Breel Embolo",
      "team": "Switzerland",
      "position": "FW",
      "goals": 2,
      "assists": 2,
      "points": 4,
      "matches": 6,
      "minutes": 534,
      "goalsPer90": 0.3,
      "pointsPer90": 0.7
    },
    {
      "rank": 31,
      "player": "Leandro Trossard",
      "team": "Belgium",
      "position": "MID",
      "goals": 2,
      "assists": 2,
      "points": 4,
      "matches": 6,
      "minutes": 561,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 32,
      "player": "Soufiane Rahimi",
      "team": "Morocco",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 6,
      "minutes": 215,
      "goalsPer90": 0.8,
      "pointsPer90": 1.3
    },
    {
      "rank": 33,
      "player": "Nicolas Pepe",
      "team": "Ivory Coast",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 4,
      "minutes": 255,
      "goalsPer90": 0.7,
      "pointsPer90": 1.1
    },
    {
      "rank": 34,
      "player": "Pape Gueye",
      "team": "Senegal",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 4,
      "minutes": 257,
      "goalsPer90": 0.7,
      "pointsPer90": 1.1
    },
    {
      "rank": 35,
      "player": "Maximiliano Araujo",
      "team": "Uruguay",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 278,
      "goalsPer90": 0.6,
      "pointsPer90": 1.0
    },
    {
      "rank": 36,
      "player": "Riyad Mahrez",
      "team": "Algeria",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 4,
      "minutes": 289,
      "goalsPer90": 0.6,
      "pointsPer90": 0.9
    },
    {
      "rank": 37,
      "player": "Ramin Rezaeian",
      "team": "Iran",
      "position": "DEF",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 3,
      "minutes": 309,
      "goalsPer90": 0.6,
      "pointsPer90": 0.9
    },
    {
      "rank": 38,
      "player": "Ruben Vargas",
      "team": "Switzerland",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 6,
      "minutes": 311,
      "goalsPer90": 0.6,
      "pointsPer90": 0.9
    },
    {
      "rank": 39,
      "player": "Ayase Ueda",
      "team": "Japan",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 4,
      "minutes": 350,
      "goalsPer90": 0.5,
      "pointsPer90": 0.8
    },
    {
      "rank": 40,
      "player": "Mostafa Ziko",
      "team": "Egypt",
      "position": "FW",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 5,
      "minutes": 399,
      "goalsPer90": 0.5,
      "pointsPer90": 0.7
    },
    {
      "rank": 41,
      "player": "Malik Tillman",
      "team": "United States",
      "position": "MID",
      "goals": 2,
      "assists": 1,
      "points": 3,
      "matches": 5,
      "minutes": 416,
      "goalsPer90": 0.4,
      "pointsPer90": 0.6
    },
    {
      "rank": 42,
      "player": "Ermin Mahmic",
      "team": "Bosnia and Herzegovina",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 88,
      "goalsPer90": 2.0,
      "pointsPer90": 2.0
    },
    {
      "rank": 43,
      "player": "Habib Diarra",
      "team": "Senegal",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 169,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 44,
      "player": "Marko Arnautovic",
      "team": "Austria",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 170,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 45,
      "player": "Mikel Merino",
      "team": "Spain",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 8,
      "minutes": 201,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 46,
      "player": "Amad Diallo",
      "team": "Ivory Coast",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 208,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 47,
      "player": "Cyle Larin",
      "team": "Canada",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 5,
      "minutes": 224,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 48,
      "player": "Anthony Elanga",
      "team": "Sweden",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 247,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 49,
      "player": "Daichi Kamada",
      "team": "Japan",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 359,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 50,
      "player": "Yasin Ayari",
      "team": "Sweden",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 4,
      "minutes": 371,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 51,
      "player": "Emam Ashour",
      "team": "Egypt",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 5,
      "minutes": 385,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 52,
      "player": "Dan Ndoye",
      "team": "Switzerland",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 6,
      "minutes": 437,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 53,
      "player": "Daniel Munoz",
      "team": "Colombia",
      "position": "DEF",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 5,
      "minutes": 449,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 54,
      "player": "Azz-Eddine Ounahi",
      "team": "Morocco",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 6,
      "minutes": 477,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 55,
      "player": "Youri Tielemans",
      "team": "Belgium",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 5,
      "minutes": 538,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 56,
      "player": "Pedro Porro",
      "team": "Spain",
      "position": "DEF",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 8,
      "minutes": 559,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 57,
      "player": "Enzo Fernandez",
      "team": "Argentina",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 8,
      "minutes": 716,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 58,
      "player": "Andreas Schjelderup",
      "team": "Norway",
      "position": "FW",
      "goals": 1,
      "assists": 3,
      "points": 4,
      "matches": 6,
      "minutes": 298,
      "goalsPer90": 0.3,
      "pointsPer90": 1.2
    },
    {
      "rank": 59,
      "player": "Anthony Gordon",
      "team": "England",
      "position": "FW",
      "goals": 1,
      "assists": 3,
      "points": 4,
      "matches": 8,
      "minutes": 443,
      "goalsPer90": 0.2,
      "pointsPer90": 0.8
    },
    {
      "rank": 60,
      "player": "Iliman-Cheikh Ndiaye",
      "team": "Senegal",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 4,
      "minutes": 134,
      "goalsPer90": 0.7,
      "pointsPer90": 2.0
    },
    {
      "rank": 61,
      "player": "Nathan-Dylan Saliba",
      "team": "Canada",
      "position": "MID",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 5,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 1.3
    },
    {
      "rank": 62,
      "player": "Alexander Isak",
      "team": "Sweden",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 4,
      "minutes": 389,
      "goalsPer90": 0.2,
      "pointsPer90": 0.7
    },
    {
      "rank": 63,
      "player": "Viktor Gyokeres",
      "team": "Sweden",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 4,
      "minutes": 401,
      "goalsPer90": 0.2,
      "pointsPer90": 0.7
    },
    {
      "rank": 64,
      "player": "Julio Enciso",
      "team": "Paraguay",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 5,
      "minutes": 432,
      "goalsPer90": 0.2,
      "pointsPer90": 0.6
    },
    {
      "rank": 65,
      "player": "Mohamed Salah",
      "team": "Egypt",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 5,
      "minutes": 470,
      "goalsPer90": 0.2,
      "pointsPer90": 0.6
    },
    {
      "rank": 66,
      "player": "Luis Diaz",
      "team": "Colombia",
      "position": "MID",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 5,
      "minutes": 523,
      "goalsPer90": 0.2,
      "pointsPer90": 0.5
    },
    {
      "rank": 67,
      "player": "Declan Rice",
      "team": "England",
      "position": "MID",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 8,
      "minutes": 618,
      "goalsPer90": 0.1,
      "pointsPer90": 0.4
    },
    {
      "rank": 68,
      "player": "Achraf Hakimi",
      "team": "Morocco",
      "position": "DEF",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 6,
      "minutes": 650,
      "goalsPer90": 0.1,
      "pointsPer90": 0.4
    },
    {
      "rank": 69,
      "player": "Promise David",
      "team": "Canada",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 5,
      "minutes": 106,
      "goalsPer90": 0.8,
      "pointsPer90": 1.7
    },
    {
      "rank": 70,
      "player": "Baris Yilmaz",
      "team": "Turkey",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 196,
      "goalsPer90": 0.5,
      "pointsPer90": 0.9
    },
    {
      "rank": 71,
      "player": "Rafael Leao",
      "team": "Portugal",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 5,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 0.9
    },
    {
      "rank": 72,
      "player": "Mousa Tamari",
      "team": "Jordan",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 230,
      "goalsPer90": 0.4,
      "pointsPer90": 0.8
    },
    {
      "rank": 73,
      "player": "Sebastian Berhalter",
      "team": "United States",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 5,
      "minutes": 232,
      "goalsPer90": 0.4,
      "pointsPer90": 0.8
    },
    {
      "rank": 74,
      "player": "Marcus Rashford",
      "team": "England",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 8,
      "minutes": 254,
      "goalsPer90": 0.4,
      "pointsPer90": 0.7
    },
    {
      "rank": 75,
      "player": "Luis Romo",
      "team": "Mexico",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 5,
      "minutes": 285,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 76,
      "player": "In-Beom Hwang",
      "team": "South Korea",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 287,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 77,
      "player": "Felix Nmecha",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 4,
      "minutes": 295,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 78,
      "player": "Kaishu Sano",
      "team": "Japan",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 4,
      "minutes": 304,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 79,
      "player": "Nathaniel Brown",
      "team": "Germany",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 3,
      "minutes": 314,
      "goalsPer90": 0.3,
      "pointsPer90": 0.6
    },
    {
      "rank": 80,
      "player": "Keito Nakamura",
      "team": "Japan",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 4,
      "minutes": 330,
      "goalsPer90": 0.3,
      "pointsPer90": 0.5
    },
    {
      "rank": 81,
      "player": "Petar Sucic",
      "team": "Croatia",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 4,
      "minutes": 339,
      "goalsPer90": 0.3,
      "pointsPer90": 0.5
    },
    {
      "rank": 82,
      "player": "Ivan Perisic",
      "team": "Croatia",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 4,
      "minutes": 413,
      "goalsPer90": 0.2,
      "pointsPer90": 0.4
    },
    {
      "rank": 83,
      "player": "Virgil van Dijk",
      "team": "Netherlands",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 4,
      "minutes": 432,
      "goalsPer90": 0.2,
      "pointsPer90": 0.4
    },
    {
      "rank": 84,
      "player": "Matias Galarza",
      "team": "Paraguay",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 5,
      "minutes": 435,
      "goalsPer90": 0.2,
      "pointsPer90": 0.4
    },
    {
      "rank": 85,
      "player": "Alex Freeman",
      "team": "United States",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 5,
      "minutes": 442,
      "goalsPer90": 0.2,
      "pointsPer90": 0.4
    },
    {
      "rank": 86,
      "player": "Desire Doue",
      "team": "France",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 8,
      "minutes": 445,
      "goalsPer90": 0.2,
      "pointsPer90": 0.4
    },
    {
      "rank": 87,
      "player": "Alex Baena",
      "team": "Spain",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 8,
      "minutes": 504,
      "goalsPer90": 0.2,
      "pointsPer90": 0.4
    },
    {
      "rank": 88,
      "player": "Lisandro Martinez",
      "team": "Argentina",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 8,
      "minutes": 703,
      "goalsPer90": 0.1,
      "pointsPer90": 0.3
    },
    {
      "rank": 89,
      "player": "Alexis Mac Allister",
      "team": "Argentina",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 8,
      "minutes": 784,
      "goalsPer90": 0.1,
      "pointsPer90": 0.2
    },
    {
      "rank": 90,
      "player": "Kaan Ayhan",
      "team": "Turkey",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 12,
      "goalsPer90": 7.5,
      "pointsPer90": 7.5
    },
    {
      "rank": 91,
      "player": "Mattias Svanberg",
      "team": "Sweden",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 26,
      "goalsPer90": 3.5,
      "pointsPer90": 3.5
    },
    {
      "rank": 92,
      "player": "Mahmoud Saber",
      "team": "Egypt",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 45,
      "goalsPer90": 2.0,
      "pointsPer90": 2.0
    },
    {
      "rank": 93,
      "player": "Ahmed Benbouali",
      "team": "Algeria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 52,
      "goalsPer90": 1.7,
      "pointsPer90": 1.7
    },
    {
      "rank": 94,
      "player": "Fiston Mayele",
      "team": "DR Congo",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 56,
      "goalsPer90": 1.6,
      "pointsPer90": 1.6
    },
    {
      "rank": 94,
      "player": "Junior Neymar",
      "team": "Brazil",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 56,
      "goalsPer90": 1.6,
      "pointsPer90": 1.6
    },
    {
      "rank": 95,
      "player": "Matias Goncalo Ramos",
      "team": "Portugal",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 59,
      "goalsPer90": 1.5,
      "pointsPer90": 1.5
    },
    {
      "rank": 96,
      "player": "Giovani Lo Celso",
      "team": "Argentina",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 8,
      "minutes": 65,
      "goalsPer90": 1.4,
      "pointsPer90": 1.4
    },
    {
      "rank": 97,
      "player": "Hasan Al Haydos",
      "team": "Qatar",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 70,
      "goalsPer90": 1.3,
      "pointsPer90": 1.3
    },
    {
      "rank": 98,
      "player": "Jovo Lukic",
      "team": "Bosnia and Herzegovina",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 77,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 99,
      "player": "Mateo Chavez",
      "team": "Mexico",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 82,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 100,
      "player": "Sasa Kalajdzic",
      "team": "Austria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 84,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 101,
      "player": "Hazem Mastouri",
      "team": "Tunisia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 93,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 102,
      "player": "Jaminton Campaz",
      "team": "Colombia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 97,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 103,
      "player": "Thelonious Aasgaard",
      "team": "Norway",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 100,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 104,
      "player": "Gessime Yassine",
      "team": "Morocco",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 105,
      "player": "Alexis Saelemaekers",
      "team": "Belgium",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 107,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 106,
      "player": "Petar Musa",
      "team": "Croatia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 116,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 107,
      "player": "Alvaro Fidalgo",
      "team": "Mexico",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 118,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 108,
      "player": "Auston Trusty",
      "team": "United States",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 123,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 109,
      "player": "Helio Varela",
      "team": "Cape Verde",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 127,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 110,
      "player": "Aymen Hussein",
      "team": "Iraq",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 129,
      "goalsPer90": 0.7,
      "pointsPer90": 0.7
    },
    {
      "rank": 111,
      "player": "Hyeon-Gyu Oh",
      "team": "South Korea",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 145,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 111,
      "player": "Nico Schlotterbeck",
      "team": "Germany",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 145,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 112,
      "player": "Giovanni Reyna",
      "team": "United States",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 156,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 113,
      "player": "Brian Cipenga",
      "team": "DR Congo",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 160,
      "goalsPer90": 0.6,
      "pointsPer90": 0.6
    },
    {
      "rank": 114,
      "player": "Ante Budimir",
      "team": "Croatia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 164,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 115,
      "player": "Gabriel Martinelli",
      "team": "Brazil",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 172,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 116,
      "player": "Leo Ostigard",
      "team": "Norway",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 182,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 117,
      "player": "Omar Rekik",
      "team": "Tunisia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 201,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 117,
      "player": "Wilson Isidor",
      "team": "Haiti",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 201,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 118,
      "player": "Ibrahim Mbaye",
      "team": "Senegal",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 203,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 118,
      "player": "Prado Mauricio",
      "team": "Paraguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 203,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 119,
      "player": "Michal Sadilek",
      "team": "Czechia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 119,
      "player": "Nikola Vlasic",
      "team": "Croatia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 119,
      "player": "Mahmoud Trezeguet",
      "team": "Egypt",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 120,
      "player": "Derrick Luckassen",
      "team": "Ghana",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 205,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 121,
      "player": "Abbosbek Fayzullaev",
      "team": "Uzbekistan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 240,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 121,
      "player": "Nilson Angulo",
      "team": "Ecuador",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 240,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 122,
      "player": "Junya Ito",
      "team": "Japan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 242,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 123,
      "player": "Livano Comenencia",
      "team": "Curacao",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 253,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 124,
      "player": "Thapelo Maseko",
      "team": "South Africa",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 256,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 125,
      "player": "Agustin Canobbio",
      "team": "Uruguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 262,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 126,
      "player": "Abdulelah Al Amri",
      "team": "Saudi Arabia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 269,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 127,
      "player": "Marcus Pedersen",
      "team": "Norway",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 271,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 127,
      "player": "Amine Gouiri",
      "team": "Algeria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 271,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 127,
      "player": "Mohammed Mohebi",
      "team": "Iran",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 271,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 127,
      "player": "Daizen Maeda",
      "team": "Japan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 271,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 128,
      "player": "John McGinn",
      "team": "Scotland",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 278,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 129,
      "player": "Romano Schmid",
      "team": "Austria",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 280,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 130,
      "player": "Nestory Irankunda",
      "team": "Australia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 286,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 131,
      "player": "Nizar Al Rashdan",
      "team": "Jordan",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 290,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 132,
      "player": "Ali Olwan",
      "team": "Jordan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 297,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 133,
      "player": "Deroy Duarte",
      "team": "Cape Verde",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 301,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 133,
      "player": "Jamal Musiala",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 301,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 133,
      "player": "Ladislav Krejci",
      "team": "Czechia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 301,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 134,
      "player": "Teboho Mokoena",
      "team": "South Africa",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 302,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 135,
      "player": "Eldor Shomurodov",
      "team": "Uzbekistan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 304,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 136,
      "player": "Finn Surman",
      "team": "New Zealand",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 307,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 137,
      "player": "Caleb Yirenkyi",
      "team": "Ghana",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 308,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 138,
      "player": "Kerim Alajbegovic",
      "team": "Bosnia and Herzegovina",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 313,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 139,
      "player": "Arda Guler",
      "team": "Turkey",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 314,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 140,
      "player": "Sidny Cabral",
      "team": "Cape Verde",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 3,
      "minutes": 321,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 141,
      "player": "Martin Baturina",
      "team": "Croatia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 344,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 142,
      "player": "Antonio Nusa",
      "team": "Norway",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 349,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 143,
      "player": "Connor Metcalfe",
      "team": "Australia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 355,
      "goalsPer90": 0.3,
      "pointsPer90": 0.3
    },
    {
      "rank": 144,
      "player": "Leroy Sane",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 361,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 144,
      "player": "Ruiz Fabian",
      "team": "Spain",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 8,
      "minutes": 361,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 145,
      "player": "Hans Vanaken",
      "team": "Belgium",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 362,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 146,
      "player": "Rafik Belghali",
      "team": "Algeria",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 363,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 147,
      "player": "Franck Kessie",
      "team": "Ivory Coast",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 390,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 147,
      "player": "Kevin Pina",
      "team": "Cape Verde",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 390,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 148,
      "player": "Jhon Arias",
      "team": "Colombia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 406,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 149,
      "player": "Gonzalo Plata",
      "team": "Ecuador",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 408,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 150,
      "player": "Marcel Sabitzer",
      "team": "Austria",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 412,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 151,
      "player": "Kevin De Bruyne",
      "team": "Belgium",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 413,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 152,
      "player": "Carlos Casemiro",
      "team": "Brazil",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 422,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 153,
      "player": "Jan Paul van Hecke",
      "team": "Netherlands",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 4,
      "minutes": 432,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 154,
      "player": "Antunes Stephen Eustaquio",
      "team": "Canada",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 444,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 155,
      "player": "Alexandre Nuno Mendes",
      "team": "Portugal",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 448,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 156,
      "player": "Joao Neves",
      "team": "Portugal",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 451,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 157,
      "player": "Yasser Ibrahim",
      "team": "Egypt",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 5,
      "minutes": 533,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 158,
      "player": "Issa Diop",
      "team": "Morocco",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 534,
      "goalsPer90": 0.2,
      "pointsPer90": 0.2
    },
    {
      "rank": 159,
      "player": "Lamine Yamal",
      "team": "Spain",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 8,
      "minutes": 612,
      "goalsPer90": 0.1,
      "pointsPer90": 0.1
    },
    {
      "rank": 160,
      "player": "Julian Alvarez",
      "team": "Argentina",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 8,
      "minutes": 632,
      "goalsPer90": 0.1,
      "pointsPer90": 0.1
    },
    {
      "rank": 161,
      "player": "Cristian Romero",
      "team": "Argentina",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 8,
      "minutes": 667,
      "goalsPer90": 0.1,
      "pointsPer90": 0.1
    },
    {
      "rank": 162,
      "player": "Granit Xhaka",
      "team": "Switzerland",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 6,
      "minutes": 670,
      "goalsPer90": 0.1,
      "pointsPer90": 0.1
    },
    {
      "rank": 163,
      "player": "Ezri Konsa",
      "team": "England",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 8,
      "minutes": 740,
      "goalsPer90": 0.1,
      "pointsPer90": 0.1
    }
  ]
};
