window.WORLD_CUP_PLAYER_STATS = {
  "generatedAt": "2026-06-19T19:36:06+00:00",
  "sources": [
    {
      "label": "Guardian Golden Boot",
      "url": "https://www.theguardian.com/football/ng-interactive/2026/jun/04/golden-boot-world-cup-2026-top-goalscorers-winner"
    },
    {
      "label": "Guardian data feed",
      "url": "https://mobile.guardianapis.com/sport/football/competitions/700/golden-boot"
    }
  ],
  "players": [
    {
      "rank": 1,
      "player": "Lionel Messi",
      "team": "Argentina",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 1,
      "minutes": 83,
      "goalsPer90": 3.3,
      "pointsPer90": 3.3
    },
    {
      "rank": 2,
      "player": "Jonathan David",
      "team": "Canada",
      "position": "FW",
      "goals": 3,
      "assists": 0,
      "points": 3,
      "matches": 2,
      "minutes": 170,
      "goalsPer90": 1.6,
      "pointsPer90": 1.6
    },
    {
      "rank": 3,
      "player": "Johan Manzambi",
      "team": "Switzerland",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 59,
      "goalsPer90": 3.1,
      "pointsPer90": 3.1
    },
    {
      "rank": 4,
      "player": "Kai Havertz",
      "team": "Germany",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 1,
      "minutes": 100,
      "goalsPer90": 1.8,
      "pointsPer90": 1.8
    },
    {
      "rank": 5,
      "player": "Yasin Ayari",
      "team": "Sweden",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 1.8,
      "pointsPer90": 1.8
    },
    {
      "rank": 5,
      "player": "Elijah Just",
      "team": "New Zealand",
      "position": "MID",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 1.8,
      "pointsPer90": 1.8
    },
    {
      "rank": 6,
      "player": "Harry Kane",
      "team": "England",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 1,
      "minutes": 102,
      "goalsPer90": 1.8,
      "pointsPer90": 1.8
    },
    {
      "rank": 7,
      "player": "Erling Braut Haaland",
      "team": "Norway",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 1,
      "minutes": 103,
      "goalsPer90": 1.7,
      "pointsPer90": 1.7
    },
    {
      "rank": 8,
      "player": "Kylian Mbappe",
      "team": "France",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 1,
      "minutes": 106,
      "goalsPer90": 1.7,
      "pointsPer90": 1.7
    },
    {
      "rank": 9,
      "player": "Folarin Balogun",
      "team": "United States",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 111,
      "goalsPer90": 1.6,
      "pointsPer90": 1.6
    },
    {
      "rank": 10,
      "player": "Cyle Larin",
      "team": "Canada",
      "position": "FW",
      "goals": 2,
      "assists": 0,
      "points": 2,
      "matches": 2,
      "minutes": 126,
      "goalsPer90": 1.4,
      "pointsPer90": 1.4
    },
    {
      "rank": 11,
      "player": "Deniz Undav",
      "team": "Germany",
      "position": "FW",
      "goals": 1,
      "assists": 2,
      "points": 3,
      "matches": 1,
      "minutes": 31,
      "goalsPer90": 2.9,
      "pointsPer90": 8.7
    },
    {
      "rank": 12,
      "player": "Nathan-Dylan Saliba",
      "team": "Canada",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 43,
      "goalsPer90": 2.1,
      "pointsPer90": 4.2
    },
    {
      "rank": 13,
      "player": "Nathaniel Brown",
      "team": "Germany",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 1,
      "minutes": 78,
      "goalsPer90": 1.2,
      "pointsPer90": 2.3
    },
    {
      "rank": 14,
      "player": "Alexander Isak",
      "team": "Sweden",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 1,
      "minutes": 94,
      "goalsPer90": 1.0,
      "pointsPer90": 1.9
    },
    {
      "rank": 15,
      "player": "Luis Diaz",
      "team": "Colombia",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 1,
      "minutes": 98,
      "goalsPer90": 0.9,
      "pointsPer90": 1.8
    },
    {
      "rank": 16,
      "player": "Viktor Gyokeres",
      "team": "Sweden",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 1.8
    },
    {
      "rank": 16,
      "player": "Ramin Rezaeian",
      "team": "Iran",
      "position": "DEF",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 1.8
    },
    {
      "rank": 17,
      "player": "Ruben Vargas",
      "team": "Switzerland",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 111,
      "goalsPer90": 0.8,
      "pointsPer90": 1.6
    },
    {
      "rank": 18,
      "player": "In-Beom Hwang",
      "team": "South Korea",
      "position": "MID",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 187,
      "goalsPer90": 0.5,
      "pointsPer90": 1.0
    },
    {
      "rank": 19,
      "player": "Breel Embolo",
      "team": "Switzerland",
      "position": "FW",
      "goals": 1,
      "assists": 1,
      "points": 2,
      "matches": 2,
      "minutes": 195,
      "goalsPer90": 0.5,
      "pointsPer90": 0.9
    },
    {
      "rank": 20,
      "player": "Ermin Mahmic",
      "team": "Bosnia and Herzegovina",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 7,
      "goalsPer90": 12.9,
      "pointsPer90": 12.9
    },
    {
      "rank": 21,
      "player": "Mattias Svanberg",
      "team": "Sweden",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 13,
      "goalsPer90": 6.9,
      "pointsPer90": 6.9
    },
    {
      "rank": 22,
      "player": "Giovanni Reyna",
      "team": "United States",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 17,
      "goalsPer90": 5.3,
      "pointsPer90": 5.3
    },
    {
      "rank": 23,
      "player": "Bradley Barcola",
      "team": "France",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 20,
      "goalsPer90": 4.5,
      "pointsPer90": 4.5
    },
    {
      "rank": 24,
      "player": "Marcus Rashford",
      "team": "England",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 24,
      "goalsPer90": 3.8,
      "pointsPer90": 3.8
    },
    {
      "rank": 25,
      "player": "Ibrahim Mbaye",
      "team": "Senegal",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 25,
      "goalsPer90": 3.6,
      "pointsPer90": 3.6
    },
    {
      "rank": 25,
      "player": "Leo Ostigard",
      "team": "Norway",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 25,
      "goalsPer90": 3.6,
      "pointsPer90": 3.6
    },
    {
      "rank": 26,
      "player": "Jaminton Campaz",
      "team": "Colombia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 29,
      "goalsPer90": 3.1,
      "pointsPer90": 3.1
    },
    {
      "rank": 27,
      "player": "Amad Diallo",
      "team": "Ivory Coast",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 43,
      "goalsPer90": 2.1,
      "pointsPer90": 2.1
    },
    {
      "rank": 28,
      "player": "Prado Mauricio",
      "team": "Paraguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 53,
      "goalsPer90": 1.7,
      "pointsPer90": 1.7
    },
    {
      "rank": 29,
      "player": "Marko Arnautovic",
      "team": "Austria",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 58,
      "goalsPer90": 1.6,
      "pointsPer90": 1.6
    },
    {
      "rank": 30,
      "player": "Nestory Irankunda",
      "team": "Australia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 64,
      "goalsPer90": 1.4,
      "pointsPer90": 1.4
    },
    {
      "rank": 31,
      "player": "Hyeon-Gyu Oh",
      "team": "South Korea",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 67,
      "goalsPer90": 1.3,
      "pointsPer90": 1.3
    },
    {
      "rank": 32,
      "player": "Jamal Musiala",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 69,
      "goalsPer90": 1.3,
      "pointsPer90": 1.3
    },
    {
      "rank": 33,
      "player": "Petar Musa",
      "team": "Croatia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 71,
      "goalsPer90": 1.3,
      "pointsPer90": 1.3
    },
    {
      "rank": 34,
      "player": "Crysencio Summerville",
      "team": "Netherlands",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 73,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 35,
      "player": "Luis Romo",
      "team": "Mexico",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 74,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 36,
      "player": "Emam Ashour",
      "team": "Egypt",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 75,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 37,
      "player": "Jovo Lukic",
      "team": "Bosnia and Herzegovina",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 77,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 38,
      "player": "Felix Nmecha",
      "team": "Germany",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 78,
      "goalsPer90": 1.2,
      "pointsPer90": 1.2
    },
    {
      "rank": 39,
      "player": "Abbosbek Fayzullaev",
      "team": "Uzbekistan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 82,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 40,
      "player": "Martin Baturina",
      "team": "Croatia",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 84,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 41,
      "player": "Maximiliano Araujo",
      "team": "Uruguay",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 85,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 41,
      "player": "Jude Bellingham",
      "team": "England",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 85,
      "goalsPer90": 1.1,
      "pointsPer90": 1.1
    },
    {
      "rank": 42,
      "player": "Romano Schmid",
      "team": "Austria",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 86,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 42,
      "player": "John McGinn",
      "team": "Scotland",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 86,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 43,
      "player": "Ismael Saibari",
      "team": "Morocco",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 92,
      "goalsPer90": 1.0,
      "pointsPer90": 1.0
    },
    {
      "rank": 44,
      "player": "Daichi Kamada",
      "team": "Japan",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 99,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 44,
      "player": "Keito Nakamura",
      "team": "Japan",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 99,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 44,
      "player": "Virgil van Dijk",
      "team": "Netherlands",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 99,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 45,
      "player": "Connor Metcalfe",
      "team": "Australia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 100,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 45,
      "player": "Livano Comenencia",
      "team": "Curacao",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 100,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 45,
      "player": "Nico Schlotterbeck",
      "team": "Germany",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 100,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 46,
      "player": "Omar Rekik",
      "team": "Tunisia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 46,
      "player": "Yoane Wissa",
      "team": "DR Congo",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 46,
      "player": "Joao Neves",
      "team": "Portugal",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 46,
      "player": "Mohammed Mohebi",
      "team": "Iran",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 101,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 47,
      "player": "Abdulelah Al Amri",
      "team": "Saudi Arabia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 102,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 48,
      "player": "Aymen Hussein",
      "team": "Iraq",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 103,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 49,
      "player": "Michal Sadilek",
      "team": "Czechia",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 104,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 49,
      "player": "Jose Vinicius Junior",
      "team": "Brazil",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 104,
      "goalsPer90": 0.9,
      "pointsPer90": 0.9
    },
    {
      "rank": 50,
      "player": "Daniel Munoz",
      "team": "Colombia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 106,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 51,
      "player": "Caleb Yirenkyi",
      "team": "Ghana",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 107,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 51,
      "player": "Ali Olwan",
      "team": "Jordan",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 1,
      "minutes": 107,
      "goalsPer90": 0.8,
      "pointsPer90": 0.8
    },
    {
      "rank": 52,
      "player": "Raul Jimenez",
      "team": "Mexico",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 164,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 53,
      "player": "Julian Quinones",
      "team": "Mexico",
      "position": "FW",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 170,
      "goalsPer90": 0.5,
      "pointsPer90": 0.5
    },
    {
      "rank": 54,
      "player": "Ladislav Krejci",
      "team": "Czechia",
      "position": "DEF",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 201,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 55,
      "player": "Teboho Mokoena",
      "team": "South Africa",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 202,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    },
    {
      "rank": 56,
      "player": "Granit Xhaka",
      "team": "Switzerland",
      "position": "MID",
      "goals": 1,
      "assists": 0,
      "points": 1,
      "matches": 2,
      "minutes": 204,
      "goalsPer90": 0.4,
      "pointsPer90": 0.4
    }
  ]
};
