window.WORLD_CUP_DATA = {
  "generatedAt": "2026-06-16",
  "sources": [
    {
      "label": "SBNation group schedule",
      "url": "https://www.sbnation.com/soccer/1117513/world-cup-schedule-2026-how-to-watch-every-match-scores-and-more"
    },
    {
      "label": "Wikipedia knockout bracket",
      "url": "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage"
    },
    {
      "label": "FIFA match schedule and venues",
      "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums"
    },
    {
      "label": "FourFourTwo full fixture venues",
      "url": "https://www.fourfourtwo.com/competition/world-cup-2026-fixtures-and-results"
    }
  ],
  "matches": [
    {
      "id": 1,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "A",
      "date": "2026-06-11",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Mexico",
      "away": "South Africa",
      "homeScore": 2,
      "awayScore": 0,
      "status": "completed",
      "network": "FOX",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Mexico+vs+South+Africa+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-15T19:13:02+00:00"
        },
        "lastCheckedAt": "2026-06-15T19:13:02+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Mexico+vs+South+Africa+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:13:33+00:00",
          "title": "Mexico vs South Africa Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=r1Afsds3ZD0",
          "channel": "FOX Sports",
          "durationText": "23 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "mexico-city"
    },
    {
      "id": 2,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "A",
      "date": "2026-06-11",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "South Korea",
      "away": "Czechia",
      "homeScore": 2,
      "awayScore": 1,
      "status": "completed",
      "network": "FS1",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+South+Korea+vs+Czechia+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-16T12:21:23+00:00",
          "title": "South Korea vs Czechia Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=QWoDfCkh7f8",
          "channel": "FOX Sports",
          "durationText": "2026 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        },
        "lastCheckedAt": "2026-06-16T12:21:23+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+South+Korea+vs+Czechia+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:13:49+00:00",
          "title": "South Korea vs Czechia Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=QWoDfCkh7f8",
          "channel": "FOX Sports",
          "durationText": "22 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "guadalajara"
    },
    {
      "id": 3,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "B",
      "date": "2026-06-12",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Canada",
      "away": "Bosnia and Herzegovina",
      "homeScore": 1,
      "awayScore": 1,
      "status": "completed",
      "network": "FOX",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Canada+vs+Bosnia+and+Herzegovina+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:03+00:00",
          "title": "Canada vs Bosnia and Herzegovina Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=cPwJaA22gWc",
          "channel": "FOX Sports",
          "durationText": "",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        },
        "lastCheckedAt": "2026-06-14T06:14:03+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Canada+vs+Bosnia+and+Herzegovina+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:03+00:00",
          "title": "Canada vs Bosnia and Herzegovina Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=n5qkHOWhFAc",
          "channel": "FOX Sports",
          "durationText": "",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "toronto"
    },
    {
      "id": 4,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "D",
      "date": "2026-06-12",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "United States",
      "away": "Paraguay",
      "homeScore": 4,
      "awayScore": 1,
      "status": "completed",
      "network": "FOX",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+United+States+vs+Paraguay+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:07+00:00",
          "title": "United States vs Paraguay Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=lpDZwAxVkc4",
          "channel": "FOX Sports",
          "durationText": "23 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        },
        "lastCheckedAt": "2026-06-14T06:14:07+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+United+States+vs+Paraguay+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:07+00:00",
          "title": "United States vs Paraguay Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=BXD1_mhODBU",
          "channel": "FOX Sports",
          "durationText": "4 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "los-angeles"
    },
    {
      "id": 5,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "B",
      "date": "2026-06-13",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Switzerland",
      "away": "Qatar",
      "homeScore": 1,
      "awayScore": 1,
      "status": "completed",
      "network": "FOX",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Switzerland+vs+Qatar+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:11+00:00",
          "title": "Qatar vs Switzerland Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=jSJs2nPJeLo",
          "channel": "FOX Sports",
          "durationText": "21 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        },
        "lastCheckedAt": "2026-06-14T06:14:11+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Switzerland+vs+Qatar+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:11+00:00",
          "title": "Qatar vs Switzerland Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=CUo5J7CUnCo",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "sf-bay"
    },
    {
      "id": 6,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "C",
      "date": "2026-06-13",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Brazil",
      "away": "Morocco",
      "homeScore": 1,
      "awayScore": 1,
      "status": "completed",
      "network": "FOX",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Brazil+vs+Morocco+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:15+00:00",
          "title": "Brazil vs Morocco Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=0rih2fCaXF4",
          "channel": "FOX Sports",
          "durationText": "21 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        },
        "lastCheckedAt": "2026-06-14T06:14:15+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=FOX+Sports+Brazil+vs+Morocco+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:15+00:00",
          "title": "Brazil vs Morocco Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=DX5wBEslnQI",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "ny-nj"
    },
    {
      "id": 7,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "C",
      "date": "2026-06-13",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Scotland",
      "away": "Haiti",
      "homeScore": 1,
      "awayScore": 0,
      "status": "completed",
      "network": "FOX",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Scotland+vs+Haiti+extended+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:22+00:00",
          "title": "Haiti vs Scotland Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=J_2Y34vSbBA",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        },
        "lastCheckedAt": "2026-06-14T06:14:22+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/results?search_query=Fox+Soccer+Scotland+vs+Haiti+highlights+2026+FIFA+World+Cup",
          "lastCheckedAt": "2026-06-14T06:14:22+00:00",
          "title": "Haiti vs Scotland Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=IW2BuhWuTqs",
          "channel": "FOX Sports",
          "durationText": "",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "youtube-search"
        }
      },
      "venueId": "boston"
    },
    {
      "id": 8,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "D",
      "date": "2026-06-14",
      "time": "00:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Australia",
      "away": "Turkey",
      "status": "completed",
      "network": "FS1",
      "venueId": "vancouver",
      "homeScore": 2,
      "awayScore": 0,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-14T15:17:28+00:00",
          "title": "Australia vs T\u00fcrkiye Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=LgT_qQktvjw",
          "channel": "FOX Sports",
          "durationText": "21 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-14T15:17:28+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-14T15:17:28+00:00",
          "title": "Australia vs T\u00fcrkiye Highlights  \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=xyKJHekC7io",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      }
    },
    {
      "id": 9,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "E",
      "date": "2026-06-14",
      "time": "13:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Germany",
      "away": "Curacao",
      "status": "completed",
      "network": "FOX",
      "venueId": "houston",
      "homeScore": 7,
      "awayScore": 1,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-14T21:41:49+00:00",
          "title": "Germany vs Cura\u00e7ao Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=xHtIzadh4Lg",
          "channel": "FOX Sports",
          "durationText": "24 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-14T21:41:49+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-14T21:41:49+00:00",
          "title": "Germany vs Cura\u00e7ao Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=cGKWqfsRDgo",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      }
    },
    {
      "id": 10,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "F",
      "date": "2026-06-14",
      "time": "16:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Netherlands",
      "away": "Japan",
      "status": "completed",
      "network": "FOX",
      "venueId": "dallas",
      "homeScore": 2,
      "awayScore": 2,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T09:24:26+00:00",
          "title": "Netherlands vs Japan Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=SaTyQMmOpPM",
          "channel": "FOX Sports",
          "durationText": "21 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-15T09:24:26+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T09:24:26+00:00",
          "title": "Netherlands vs Japan Highlights \ud83c\udf0e\ud83c\udfc62026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=m7sQP_AZ5vM",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      }
    },
    {
      "id": 11,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "E",
      "date": "2026-06-14",
      "time": "19:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Ivory Coast",
      "away": "Ecuador",
      "status": "completed",
      "network": "FS1",
      "venueId": "philadelphia",
      "homeScore": 1,
      "awayScore": 0,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T09:24:29+00:00",
          "title": "Ivory Coast vs Ecuador Extended Highlights \ud83c\udf0e\ud83c\udfc62026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=j6uB9LcLMms",
          "channel": "FOX Sports",
          "durationText": "21 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-15T09:24:29+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T09:24:29+00:00",
          "title": "Ivory Coast vs Ecuador Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=pBk8BjA-X4Y",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      }
    },
    {
      "id": 12,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "F",
      "date": "2026-06-14",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Sweden",
      "away": "Tunisia",
      "status": "completed",
      "network": "FS1",
      "venueId": "monterrey",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T09:24:31+00:00",
          "title": "Sweden vs Tunisia Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=F47z0suCV7Y",
          "channel": "FOX Sports",
          "durationText": "21 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-15T09:24:31+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T09:24:31+00:00",
          "title": "Sweden vs Tunisia Highlights | 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=MWsgrEPIni4",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      },
      "homeScore": 5,
      "awayScore": 1
    },
    {
      "id": 13,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "H",
      "date": "2026-06-15",
      "time": "12:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Spain",
      "away": "Cabo Verde",
      "status": "completed",
      "network": "FOX",
      "venueId": "atlanta",
      "homeScore": 0,
      "awayScore": 0,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T18:39:07+00:00",
          "title": "Spain vs Cape Verde Extended Highlights \ud83c\udf0e\ud83c\udfc62026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=wzKYVElYRrw",
          "channel": "FOX Sports",
          "durationText": "22 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-15T18:39:07+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T18:39:07+00:00",
          "title": "Spain vs Cape Verde Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=YnWF8IMcqgg",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      }
    },
    {
      "id": 14,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "G",
      "date": "2026-06-15",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Belgium",
      "away": "Egypt",
      "status": "completed",
      "network": "FOX",
      "venueId": "seattle",
      "homeScore": 1,
      "awayScore": 1,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T21:48:49+00:00",
          "title": "Belgium vs Egypt Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=gQOgcN7_IZE",
          "channel": "FOX Sports",
          "durationText": "23 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-15T21:48:49+00:00",
        "short": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-15T21:48:49+00:00",
          "title": "Belgium vs Egypt Highlights \ud83c\udf0e\ud83c\udfc62026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=o_3t0d8x9JY",
          "channel": "FOX Sports",
          "durationText": "8 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        }
      }
    },
    {
      "id": 15,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "H",
      "date": "2026-06-15",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Saudi Arabia",
      "away": "Uruguay",
      "status": "completed",
      "network": "FS1",
      "venueId": "miami",
      "homeScore": 1,
      "awayScore": 1,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-16T00:42:56+00:00",
          "title": "Saudi Arabia vs Uruguay Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=Tz9R1OYdTSs",
          "channel": "FOX Sports",
          "durationText": "16 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-16T00:42:56+00:00"
      }
    },
    {
      "id": 16,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "G",
      "date": "2026-06-15",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Iran",
      "away": "New Zealand",
      "homeScore": 2,
      "awayScore": 2,
      "status": "completed",
      "network": "FS1",
      "venueId": "los-angeles",
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-16T06:00:57+00:00",
          "title": "Iran vs New Zealand Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=UZ_7qFbFYRY",
          "channel": "FOX Sports",
          "durationText": "17 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-16T06:00:57+00:00"
      }
    },
    {
      "id": 17,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "I",
      "date": "2026-06-16",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "France",
      "away": "Senegal",
      "status": "completed",
      "network": "FOX",
      "venueId": "ny-nj",
      "homeScore": 3,
      "awayScore": 1,
      "videos": {
        "extended": {
          "searchUrl": "https://www.youtube.com/@foxsports/videos",
          "lastCheckedAt": "2026-06-16T21:48:13+00:00",
          "title": "France vs Senegal Extended Highlights \ud83c\udf0e\ud83c\udfc6 2026 FIFA World Cup\u2122",
          "url": "https://www.youtube.com/watch?v=SlmYDbzHqjg",
          "channel": "FOX Sports",
          "durationText": "17 min",
          "channelVerified": true,
          "spoilerSafeTitle": true,
          "source": "foxsports-channel"
        },
        "lastCheckedAt": "2026-06-16T21:48:13+00:00"
      }
    },
    {
      "id": 18,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "I",
      "date": "2026-06-16",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Iraq",
      "away": "Norway",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "boston"
    },
    {
      "id": 19,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "J",
      "date": "2026-06-16",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Argentina",
      "away": "Algeria",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "kansas-city"
    },
    {
      "id": 20,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "J",
      "date": "2026-06-17",
      "time": "00:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Austria",
      "away": "Jordan",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "sf-bay"
    },
    {
      "id": 21,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "K",
      "date": "2026-06-17",
      "time": "13:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Portugal",
      "away": "DR Congo",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "houston"
    },
    {
      "id": 22,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "L",
      "date": "2026-06-17",
      "time": "16:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "England",
      "away": "Croatia",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "dallas"
    },
    {
      "id": 23,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "L",
      "date": "2026-06-17",
      "time": "19:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Ghana",
      "away": "Panama",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "toronto"
    },
    {
      "id": 24,
      "stage": "Group",
      "round": "Matchday 1",
      "group": "K",
      "date": "2026-06-17",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Uzbekistan",
      "away": "Colombia",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "mexico-city"
    },
    {
      "id": 25,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "A",
      "date": "2026-06-18",
      "time": "12:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Czechia",
      "away": "South Africa",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "atlanta"
    },
    {
      "id": 26,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "B",
      "date": "2026-06-18",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Switzerland",
      "away": "Bosnia and Herzegovina",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "los-angeles"
    },
    {
      "id": 27,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "B",
      "date": "2026-06-18",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Canada",
      "away": "Qatar",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "vancouver"
    },
    {
      "id": 28,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "A",
      "date": "2026-06-18",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Mexico",
      "away": "South Korea",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "guadalajara"
    },
    {
      "id": 29,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "D",
      "date": "2026-06-19",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "United States",
      "away": "Australia",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "seattle"
    },
    {
      "id": 30,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "C",
      "date": "2026-06-19",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Scotland",
      "away": "Morocco",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "boston"
    },
    {
      "id": 31,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "C",
      "date": "2026-06-19",
      "time": "20:30",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Brazil",
      "away": "Haiti",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "philadelphia"
    },
    {
      "id": 32,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "D",
      "date": "2026-06-19",
      "time": "23:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Turkey",
      "away": "Paraguay",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "sf-bay"
    },
    {
      "id": 33,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "F",
      "date": "2026-06-20",
      "time": "13:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Netherlands",
      "away": "Sweden",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "houston"
    },
    {
      "id": 34,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "E",
      "date": "2026-06-20",
      "time": "16:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Germany",
      "away": "Ivory Coast",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "toronto"
    },
    {
      "id": 35,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "E",
      "date": "2026-06-20",
      "time": "20:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Ecuador",
      "away": "Curacao",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "kansas-city"
    },
    {
      "id": 36,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "F",
      "date": "2026-06-21",
      "time": "00:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Tunisia",
      "away": "Japan",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "monterrey"
    },
    {
      "id": 37,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "H",
      "date": "2026-06-21",
      "time": "12:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Spain",
      "away": "Saudi Arabia",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "atlanta"
    },
    {
      "id": 38,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "G",
      "date": "2026-06-21",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Belgium",
      "away": "Iran",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "los-angeles"
    },
    {
      "id": 39,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "H",
      "date": "2026-06-21",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Uruguay",
      "away": "Cabo Verde",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "miami"
    },
    {
      "id": 40,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "G",
      "date": "2026-06-21",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "New Zealand",
      "away": "Egypt",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "vancouver"
    },
    {
      "id": 41,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "J",
      "date": "2026-06-22",
      "time": "13:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Argentina",
      "away": "Austria",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "dallas"
    },
    {
      "id": 42,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "I",
      "date": "2026-06-22",
      "time": "17:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "France",
      "away": "Iraq",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "philadelphia"
    },
    {
      "id": 43,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "I",
      "date": "2026-06-22",
      "time": "20:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Norway",
      "away": "Senegal",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "ny-nj"
    },
    {
      "id": 44,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "J",
      "date": "2026-06-22",
      "time": "23:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Jordan",
      "away": "Algeria",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "sf-bay"
    },
    {
      "id": 45,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "K",
      "date": "2026-06-23",
      "time": "13:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Portugal",
      "away": "Uzbekistan",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "houston"
    },
    {
      "id": 46,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "L",
      "date": "2026-06-23",
      "time": "16:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "England",
      "away": "Ghana",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "boston"
    },
    {
      "id": 47,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "L",
      "date": "2026-06-23",
      "time": "19:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Panama",
      "away": "Croatia",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "toronto"
    },
    {
      "id": 48,
      "stage": "Group",
      "round": "Matchday 2",
      "group": "K",
      "date": "2026-06-23",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Colombia",
      "away": "DR Congo",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "guadalajara"
    },
    {
      "id": 49,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "B",
      "date": "2026-06-24",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Switzerland",
      "away": "Canada",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "vancouver"
    },
    {
      "id": 50,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "B",
      "date": "2026-06-24",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Bosnia and Herzegovina",
      "away": "Qatar",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "seattle"
    },
    {
      "id": 51,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "C",
      "date": "2026-06-24",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Morocco",
      "away": "Haiti",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "atlanta"
    },
    {
      "id": 52,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "C",
      "date": "2026-06-24",
      "time": "18:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Scotland",
      "away": "Brazil",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "miami"
    },
    {
      "id": 53,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "A",
      "date": "2026-06-24",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "South Africa",
      "away": "South Korea",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "monterrey"
    },
    {
      "id": 54,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "A",
      "date": "2026-06-24",
      "time": "21:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Czechia",
      "away": "Mexico",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "mexico-city"
    },
    {
      "id": 55,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "E",
      "date": "2026-06-25",
      "time": "16:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Curacao",
      "away": "Ivory Coast",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "philadelphia"
    },
    {
      "id": 56,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "E",
      "date": "2026-06-25",
      "time": "16:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Ecuador",
      "away": "Germany",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "ny-nj"
    },
    {
      "id": 57,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "F",
      "date": "2026-06-25",
      "time": "19:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Tunisia",
      "away": "Netherlands",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "kansas-city"
    },
    {
      "id": 58,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "F",
      "date": "2026-06-25",
      "time": "19:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Japan",
      "away": "Sweden",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "dallas"
    },
    {
      "id": 59,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "D",
      "date": "2026-06-25",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Turkey",
      "away": "United States",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "los-angeles"
    },
    {
      "id": 60,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "D",
      "date": "2026-06-25",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Paraguay",
      "away": "Australia",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "sf-bay"
    },
    {
      "id": 61,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "I",
      "date": "2026-06-26",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Norway",
      "away": "France",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "boston"
    },
    {
      "id": 62,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "I",
      "date": "2026-06-26",
      "time": "15:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Senegal",
      "away": "Iraq",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "toronto"
    },
    {
      "id": 63,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "H",
      "date": "2026-06-26",
      "time": "20:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Cabo Verde",
      "away": "Saudi Arabia",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "houston"
    },
    {
      "id": 64,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "H",
      "date": "2026-06-26",
      "time": "20:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Uruguay",
      "away": "Spain",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "guadalajara"
    },
    {
      "id": 65,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "G",
      "date": "2026-06-26",
      "time": "23:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "New Zealand",
      "away": "Belgium",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "vancouver"
    },
    {
      "id": 66,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "G",
      "date": "2026-06-26",
      "time": "23:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Egypt",
      "away": "Iran",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "seattle"
    },
    {
      "id": 67,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "L",
      "date": "2026-06-27",
      "time": "17:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Panama",
      "away": "England",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "ny-nj"
    },
    {
      "id": 68,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "L",
      "date": "2026-06-27",
      "time": "17:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Croatia",
      "away": "Ghana",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "philadelphia"
    },
    {
      "id": 69,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "K",
      "date": "2026-06-27",
      "time": "19:30",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Colombia",
      "away": "Portugal",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "miami"
    },
    {
      "id": 70,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "K",
      "date": "2026-06-27",
      "time": "19:30",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "DR Congo",
      "away": "Uzbekistan",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "atlanta"
    },
    {
      "id": 71,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "J",
      "date": "2026-06-27",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Algeria",
      "away": "Austria",
      "status": "scheduled",
      "network": "FS1",
      "venueId": "kansas-city"
    },
    {
      "id": 72,
      "stage": "Group",
      "round": "Matchday 3",
      "group": "J",
      "date": "2026-06-27",
      "time": "22:00",
      "offset": "-04:00",
      "timezoneLabel": "ET",
      "home": "Jordan",
      "away": "Argentina",
      "status": "scheduled",
      "network": "FOX",
      "venueId": "dallas"
    },
    {
      "id": 73,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-28",
      "time": null,
      "home": "Runner-up Group A",
      "away": "Runner-up Group B",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "los-angeles"
    },
    {
      "id": 74,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-28",
      "time": null,
      "home": "Winner Group E",
      "away": "Best 3rd Group A/B/C/D/F",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "boston"
    },
    {
      "id": 75,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-28",
      "time": null,
      "home": "Winner Group F",
      "away": "Runner-up Group C",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "monterrey"
    },
    {
      "id": 76,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-29",
      "time": null,
      "home": "Winner Group C",
      "away": "Runner-up Group F",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "houston"
    },
    {
      "id": 77,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-29",
      "time": null,
      "home": "Winner Group I",
      "away": "Best 3rd Group C/D/F/G/H",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "ny-nj"
    },
    {
      "id": 78,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-29",
      "time": null,
      "home": "Runner-up Group E",
      "away": "Runner-up Group I",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "dallas"
    },
    {
      "id": 79,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-30",
      "time": null,
      "home": "Winner Group A",
      "away": "Best 3rd Group C/E/F/H/I",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "mexico-city"
    },
    {
      "id": 80,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-30",
      "time": null,
      "home": "Winner Group L",
      "away": "Best 3rd Group E/H/I/J/K",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "atlanta"
    },
    {
      "id": 81,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-06-30",
      "time": null,
      "home": "Winner Group D",
      "away": "Best 3rd Group B/E/F/I/J",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "sf-bay"
    },
    {
      "id": 82,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-01",
      "time": null,
      "home": "Winner Group G",
      "away": "Best 3rd Group A/E/H/I/J",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "seattle"
    },
    {
      "id": 83,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-01",
      "time": null,
      "home": "Runner-up Group K",
      "away": "Runner-up Group L",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "toronto"
    },
    {
      "id": 84,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-01",
      "time": null,
      "home": "Winner Group H",
      "away": "Runner-up Group J",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "los-angeles"
    },
    {
      "id": 85,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-02",
      "time": null,
      "home": "Winner Group B",
      "away": "Best 3rd Group E/F/G/I/J",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "vancouver"
    },
    {
      "id": 86,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-02",
      "time": null,
      "home": "Winner Group J",
      "away": "Runner-up Group H",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "miami"
    },
    {
      "id": 87,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-03",
      "time": null,
      "home": "Winner Group K",
      "away": "Best 3rd Group D/E/I/J/L",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "kansas-city"
    },
    {
      "id": 88,
      "stage": "Round of 32",
      "round": "Knockout",
      "date": "2026-07-03",
      "time": null,
      "home": "Runner-up Group D",
      "away": "Runner-up Group G",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "dallas"
    },
    {
      "id": 89,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-04",
      "time": null,
      "home": "Winner Match 73",
      "away": "Winner Match 75",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "philadelphia"
    },
    {
      "id": 90,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-04",
      "time": null,
      "home": "Winner Match 74",
      "away": "Winner Match 77",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "houston"
    },
    {
      "id": 91,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-05",
      "time": null,
      "home": "Winner Match 76",
      "away": "Winner Match 78",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "ny-nj"
    },
    {
      "id": 92,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-05",
      "time": null,
      "home": "Winner Match 79",
      "away": "Winner Match 80",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "mexico-city"
    },
    {
      "id": 93,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-06",
      "time": null,
      "home": "Winner Match 83",
      "away": "Winner Match 84",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "dallas"
    },
    {
      "id": 94,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-06",
      "time": null,
      "home": "Winner Match 81",
      "away": "Winner Match 82",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "seattle"
    },
    {
      "id": 95,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-07",
      "time": null,
      "home": "Winner Match 86",
      "away": "Winner Match 88",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "atlanta"
    },
    {
      "id": 96,
      "stage": "Round of 16",
      "round": "Knockout",
      "date": "2026-07-07",
      "time": null,
      "home": "Winner Match 85",
      "away": "Winner Match 87",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "vancouver"
    },
    {
      "id": 97,
      "stage": "Quarterfinals",
      "round": "Knockout",
      "date": "2026-07-09",
      "time": null,
      "home": "Winner Match 89",
      "away": "Winner Match 90",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "boston"
    },
    {
      "id": 98,
      "stage": "Quarterfinals",
      "round": "Knockout",
      "date": "2026-07-10",
      "time": null,
      "home": "Winner Match 93",
      "away": "Winner Match 94",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "los-angeles"
    },
    {
      "id": 99,
      "stage": "Quarterfinals",
      "round": "Knockout",
      "date": "2026-07-10",
      "time": null,
      "home": "Winner Match 91",
      "away": "Winner Match 92",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "miami"
    },
    {
      "id": 100,
      "stage": "Quarterfinals",
      "round": "Knockout",
      "date": "2026-07-11",
      "time": null,
      "home": "Winner Match 95",
      "away": "Winner Match 96",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "kansas-city"
    },
    {
      "id": 101,
      "stage": "Semifinals",
      "round": "Knockout",
      "date": "2026-07-14",
      "time": null,
      "home": "Winner Match 97",
      "away": "Winner Match 98",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "dallas"
    },
    {
      "id": 102,
      "stage": "Semifinals",
      "round": "Knockout",
      "date": "2026-07-15",
      "time": null,
      "home": "Winner Match 99",
      "away": "Winner Match 100",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "atlanta"
    },
    {
      "id": 103,
      "stage": "Third Place",
      "round": "Knockout",
      "date": "2026-07-18",
      "time": null,
      "home": "Loser Match 101",
      "away": "Loser Match 102",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "miami"
    },
    {
      "id": 104,
      "stage": "Final",
      "round": "Knockout",
      "date": "2026-07-19",
      "time": null,
      "home": "Winner Match 101",
      "away": "Winner Match 102",
      "status": "scheduled",
      "network": "TBD",
      "venueId": "ny-nj"
    }
  ],
  "scheduleUpdatedAt": "2026-06-16T21:46:11+00:00",
  "scheduleSourceUrl": "https://www.sbnation.com/soccer/1117513/world-cup-schedule-2026-how-to-watch-every-match-scores-and-more",
  "venues": [
    {
      "id": "vancouver",
      "fifaName": "BC Place Vancouver",
      "stadium": "BC Place",
      "city": "Vancouver",
      "region": "British Columbia",
      "country": "Canada",
      "mapX": 17,
      "mapY": 21
    },
    {
      "id": "seattle",
      "fifaName": "Seattle Stadium",
      "stadium": "Lumen Field",
      "city": "Seattle",
      "region": "Washington",
      "country": "United States",
      "mapX": 18,
      "mapY": 27
    },
    {
      "id": "sf-bay",
      "fifaName": "San Francisco Bay Area Stadium",
      "stadium": "Levi's Stadium",
      "city": "Santa Clara",
      "region": "California",
      "country": "United States",
      "mapX": 17,
      "mapY": 49
    },
    {
      "id": "los-angeles",
      "fifaName": "Los Angeles Stadium",
      "stadium": "SoFi Stadium",
      "city": "Inglewood",
      "region": "California",
      "country": "United States",
      "mapX": 19,
      "mapY": 58
    },
    {
      "id": "guadalajara",
      "fifaName": "Estadio Guadalajara",
      "stadium": "Estadio Akron",
      "city": "Zapopan",
      "region": "Jalisco",
      "country": "Mexico",
      "mapX": 40,
      "mapY": 78
    },
    {
      "id": "monterrey",
      "fifaName": "Estadio Monterrey",
      "stadium": "Estadio BBVA",
      "city": "Guadalupe",
      "region": "Nuevo Leon",
      "country": "Mexico",
      "mapX": 49,
      "mapY": 70
    },
    {
      "id": "mexico-city",
      "fifaName": "Mexico City Stadium",
      "stadium": "Estadio Azteca",
      "city": "Mexico City",
      "region": "CDMX",
      "country": "Mexico",
      "mapX": 47,
      "mapY": 84
    },
    {
      "id": "dallas",
      "fifaName": "Dallas Stadium",
      "stadium": "AT&T Stadium",
      "city": "Arlington",
      "region": "Texas",
      "country": "United States",
      "mapX": 48,
      "mapY": 68
    },
    {
      "id": "houston",
      "fifaName": "Houston Stadium",
      "stadium": "NRG Stadium",
      "city": "Houston",
      "region": "Texas",
      "country": "United States",
      "mapX": 51,
      "mapY": 74
    },
    {
      "id": "kansas-city",
      "fifaName": "Kansas City Stadium",
      "stadium": "Arrowhead Stadium",
      "city": "Kansas City",
      "region": "Missouri",
      "country": "United States",
      "mapX": 52,
      "mapY": 56
    },
    {
      "id": "atlanta",
      "fifaName": "Atlanta Stadium",
      "stadium": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "region": "Georgia",
      "country": "United States",
      "mapX": 65,
      "mapY": 67
    },
    {
      "id": "miami",
      "fifaName": "Miami Stadium",
      "stadium": "Hard Rock Stadium",
      "city": "Miami Gardens",
      "region": "Florida",
      "country": "United States",
      "mapX": 73,
      "mapY": 78
    },
    {
      "id": "philadelphia",
      "fifaName": "Philadelphia Stadium",
      "stadium": "Lincoln Financial Field",
      "city": "Philadelphia",
      "region": "Pennsylvania",
      "country": "United States",
      "mapX": 77,
      "mapY": 49
    },
    {
      "id": "ny-nj",
      "fifaName": "New York New Jersey Stadium",
      "stadium": "MetLife Stadium",
      "city": "East Rutherford",
      "region": "New Jersey",
      "country": "United States",
      "mapX": 79,
      "mapY": 47
    },
    {
      "id": "boston",
      "fifaName": "Boston Stadium",
      "stadium": "Gillette Stadium",
      "city": "Foxborough",
      "region": "Massachusetts",
      "country": "United States",
      "mapX": 84,
      "mapY": 42
    },
    {
      "id": "toronto",
      "fifaName": "Toronto Stadium",
      "stadium": "BMO Field",
      "city": "Toronto",
      "region": "Ontario",
      "country": "Canada",
      "mapX": 70,
      "mapY": 35
    }
  ]
};
